### PR TITLE
refactor(dashboard): rewriting these components

### PR DESCRIPTION
**Pull request by scottdickerson**
rewriting the dashboard components to make it easier to add a card that will load it's data

### CODE REVIEW

**Comment by tay1orjones** [comment]
Should this go into `master`?

**Comment by tay1orjones** [comment]
ImageCard expand to full screen on basic story gives a console error
```
Uncaught TypeError: onCardAction is not a function
    at onClick (Card.jsx:333)
```

**Comment by scottdickerson** [comment]
thanks @tay1orjones I fixed that one, any other issues?

**Pull request merged**
