### PR TITLE
fix(valuecard): datastate texts removed for size smallwide

### LINKED ISSUE #304: [Release] v2.0.0
Epic containing all the work items leading up to v2 release.

### Must Haves:
- [x] Create `v2` label for GitHub issues feeding into v2
- [x] Create `beta` branch to contain this work
- [x] Update semantic release to publish prerelease from `beta` - #276 
- [x] Update storybook deploy to support `beta` branch, consistent static url - #305 
- [x] Upgrade Carbon to v10, Update our components #154
- [x] Consolidate our components with Carbon variants - #369 
- [x] Provide wrapper components for all Carbon react components, #355 
- [x] Update to Carbon v10.4 - #436
- [ ] Merge updates from `master` into `beta` - #437

### Nice To Haves:

- [ ] Align Components to Patterns -  #354
- [x] Theme Storybook for consistent branding - #309
- [ ] Dashboard/monitoring components updated to support Carbon v10 - #306 
  - These are unlikely to be migrated before other updates have been made. They're currently experimental and baked with Carbon v9. Without the update, these components will likely not be included in the initial v2 release although we can upgrade them at any point thereafter. Existing development requirements can continue to be delivered to the v.1.x release
- [ ] Unify Layout, Spacing, and Color to Carbon Tokens #303 
- [ ] Refactor styling approach from styled-components to scss to align with Carbon - #370 

~- [ ] Migrate WIoT Theme file to this library - #332~

### LINKED ISSUE #1009: [Dashboard] Tile alert states visual issues
These looked good a week ago but seem to have regressed a bit?
1. Padding on bottom of "SmallWide" is missing
2. Tooltip for text appears at lower z-index
Screen Shot 2020-03-05 at 1 11 07 PM
Screen Shot 2020-03-05 at 1 11 03 PM

### PR DESCRIPTION
**Pull request by bjornalm**
Closes #1009

**Summary**
The content of the data state rendering in the ValueCard did not fit in the available height of size SMALLWIDE. The flex column content was rendered differently in Chrome and FF. In Chrome the bottom padding was keps and the content was pushed upp overflowing into the card header (which kind of looked okay), but in FF the content was pushed down resulting in the bottom padding not being visible.

**Change List (commits, features, bugs, etc)**
Regardless of the difference between the browsers, the actual problem was that the content did not fit vertically, which has now been fixed by adding the SMALLWIDE to the same rendering as SMALL and MEDIUMTHIN.

Added a unit test that verifies the fix.

**Acceptance Test (how to verify the PR)**
Check the ValueCard stories with using size SMALLWIDE and make sure they look correct and the same in webkit browsers and FF

### CODE REVIEW

**Comment by tay1orjones** [comment]
Is #304 the issue you meant to link? That's the old v2 epic issue.

**Comment by bjornalm** [comment]
@tay1orjones 
Regarding the number 304. This is bit confusing to me. Here is the issue but it looks like it belongs to another tracker https://github.ibm.com/Watson-IoT/pal-tracking/issues/304

**Comment by tay1orjones** [comment]
@bjornalm ah, yes. The github.ibm.com url is for our internal tracking. Use the full link when reference these issues to prevent mis-linking an issue present in this external github.com repo. Looks like you updated the original comment with the proper issue. 👍 

Sorry for the confusion as we need to track issues for internal reporting purposes.

**Pull request merged**
