### PR TITLE
fix(inlinenotification): use lowContrast inline notification

### PR DESCRIPTION
**Pull request by leetosc**
Closes #

**Summary**

- add `lowContrast` to `InlineNotification` used in PageWizard

**Change List (commits, features, bugs, etc)**

- PageWizard

**Acceptance Test (how to verify the PR)**

- PageWizard

### CODE REVIEW

**Comment by tay1orjones** [comment]
Is using the low contrast version of inline notification a change from design?

cc @lukefirth @bryancboyd

**Comment by leetosc** [comment]
Yes, it came up while fixing this issue: https://github.ibm.com/wiotp/monitoring-dashboard/issues/533

**Comment by davidicus** [comment]
Where does the yarn.lock change come from? If we have no changes to our package list there shouldn't be a need to update yarn.lock

**Pull request merged**
