### PR TITLE
feat(button): add icon selection button

### LINKED ISSUE #1244: [Component Proposal] Icon selection button
[Internal Watson-IoT/pal-tracking#153](https://github.ibm.com/Watson-IoT/pal-tracking/issues/153)

### Summary

Originally from internal issue:

> **What is the rationale for this contribution.**
> A large icon denoting something a user may wish to select and/or enable such as picking a particular chart type in a compact manner.
> 
> **Detail the intended behavior**
> The icon (20px) sits inside a larger square container (seemingly 48px) and may have a series of states.
> 
> From a default, or recommended state, the user can click to enable the icon selection, and click again (or elsewhere depending on the usage) to return to the default state.
> image

**Additional context**
Further clarification from @lukefirth originally on internal issue:

> In this the important this is the states that differentiate it from a traditional button.
> 
> It may be unselected:
> - By default it has a ghost styling.
> - It can also have the 'recommended' styling of the green border 
> - Standard hover and disable states
> 
> However when clicked, not only will it trigger whatever selection it is tied to do something, it will also go to its active state and 'stay there' until a user either clicks it again, or clicks on a different selection button. In that way, it is more like a button style implementation of a checkbox or radio _button_ (heh).

### PR DESCRIPTION
**Pull request by tay1orjones**
Closes #1244

**Summary**

- Adds a new kind option to Button

**Change List (commits, features, bugs, etc)**

- Add new `kind`, `selected`, and `recommended` props and associated visual styling
- Update storybook with new story showing a singular button of the new kind, new knobs have been added for `recommended` and `selected`. The story is also an example of how to utilize useState to make the `selected` state "sticky" as called for by the initial design intent in #1244 
- Added tests/snapshots

**Acceptance Test (how to verify the PR)**

- Test [the new story](https://deploy-preview-1245--carbon-addons-iot-react.netlify.app/?path=/story/watson-iot-button--icon-selection-buttons) knobs to view the recommended state and click the button to see visual states change for sticky `selected` with and without `recommended`
- Also verify the interaction and style is consistent across all 3 button sizes.

### CODE REVIEW

**Comment by tay1orjones** [comment]
@lukefirth please review for interaction/visual approval

**Comment by lukefirth** [comment]
@tay1orjones couple of notes:

 1.  Can we get a 3 x 3 (with 8px padding between) story example for the selection button, have one as recommended - and naturally have it so when you pick one, it deselects the last? This would be a good demonstration of the usefulness of it to off a 'palette' of options to a user rather than just the singular 'on/off' setting. Or again, this might be another example where building a demo (if we had that) would be much better than making a story specifically...


2. Just a minor detail on the visual I think - the default state when not clicked is currently interactive-01 (blue) in the story, but should be icon-01 (black) until it is selected, at which point it goes blue.

**Comment by tay1orjones** [comment]
@lukefirth This is just the first piece for the button itself. A more intentional example as you describe will be provided with the second phase of this: 
>[Watson-IoT/pal-tracking#174 - `Dropdown with selection icon buttons inside`](https://github.ibm.com/watson-iot/pal-tracking/issues/174)
>
> 

I'll update the visual black/blue state

**Comment by tay1orjones** [comment]
@lukefirth Visual state color has been corrected.

**Comment by tay1orjones** [comment]
@sstone2423 It's not intentional. That delay has been present in our storybook for quite a while and effects all the button stories. I think it has something to do with the Storybook environment? Or perhaps the way we config those stories - honestly I haven't debugged it yet.

There's no delay if you spin up a `npx create-iot-react-app test-app` and test it though.

**Comment by sstone2423** [comment]
@tay1orjones Oh funky. Sounds good

**Pull request merged**
