### PR TITLE
fix(bug): TileCatalog: hide button if no pagination

### PR DESCRIPTION
**Pull request by billpereira**
**Summary**

- If no more than 1 page, hide the buttons

**Change List (commits, features, bugs, etc)**

-bug

**Related Issues**

- Closes IBM/carbon-addons-iot-react#252

**Acceptance Test (how to verify the PR)**

- tests here

### CODE REVIEW

**Comment by scottdickerson** [comment]
This code works great, thank you for fixing! Can you make one very small style change, can you right-justify the Page 1 of 1 instead of having the 6rem margin-right. Picture below:

image

**Comment by billpereira** [comment]
will fix that ;) Didn't know if was better to have it always on same place or moving if no buttons

**Comment by scottdickerson** [comment]
this looks great @billpereira if you can just resolve the merge conflicts I'll accept.  thanks!

**Comment by billpereira** [comment]
@scottdickerson I have removed the conflicts

**Pull request merged**
