### PR TITLE
Row actions overflow update

### LINKED ISSUE #1087: [Table] Row actions (overflow) should expose hasDivider and isDelete
### Summary

<sub>[Internal issue #373](https://github.ibm.com/Watson-IoT/pal-tracking/issues/373)</sub>

The prop interface for `rowActions` in an overflow menu should allow you to specify if:

1. The item has a divider
2. The item is a "delete" type (hover highlighted red)

**Additional context**

https://github.com/IBM/carbon-addons-iot-react/blob/master/src/components/Table/TableBody/RowActionsCell/RowActionsCell.jsx#L219

I'd suggest extending the prop interface for a row action to support these two properties:

```
rowActions: [{
  id: 'edit',
  isOverflow: true,
  labelText: 'Edit',
  hasDivider: true,
  isDelete: false,
},{
  id: 'delete',
  isOverflow: true,
  labelText: 'Delete',
  isDelete: true,  // also adds divider
}]
```

Example from Carbon story:

https://react.carbondesignsystem.com/?path=/story/overflowmenu--basic

image

### Specific timeline issues / requests

This is related to an upcoming release within 1-2 months.

### Available extra resources

I'd recommend @rawa-resul work on this.

### PR DESCRIPTION
**Pull request by rawa-resul**
Closes #1087

**Summary**

- Added the option to specify if an item in rowActions has a divider or is a delete type.
Screenshot 2020-04-14 at 20 18 13

**Change List (commits, features, bugs, etc)**

- Added `hasDivider `and `isDelete` prop to OverFlowMenuItem in RowActionsCell
- Added `hasDivider` amd `isDelete` to default/propTypes
- Added a few more elements to `rowActions` to incorporate the new attributes

**Acceptance Test (how to verify the PR)**

- Add a new element to `rowActions` in TableBodyRow story and set `hasDivider` and/or `isDelete` to `true` to see the new appended styles

### CODE REVIEW

**Comment by tay1orjones** [comment]
Do we need to expose this functionality through `Table`/`StatefulTable`? @bryancboyd

**Comment by bryancboyd** [comment]
Good catch @tay1orjones.  @rawa-resul we'll need to also update the Table props to allow passing in these additional props on a table row.

To validate the design, I'd suggest updating the `with row expansion and actions` Table story to use the new separator and delete option:

image

**Comment by rawa-resul** [comment]
@tay1orjones @bryancboyd 
Thanks for pointing that out. I have added the required props in `Table.story.jsx` to include `hasDivider` and `isDelete` type. The changes should be visible in:

- Stateful Example with expansion and column resize
- Stateful Example with row nesting and fixed columns
- With row expansion and actions
- Stateful Example with I18N strings

**Comment by rawa-resul** [comment]
@tay1orjones My bad, I completely missed the RowActionPropTypes. I have added these now.

**Pull request merged**
