### PR TITLE
6277 dashboard grid is editable tile jump

### LINKED ISSUE #780: [DashboardGrid] isEditable causes tiles to jump on initial render
<sub>[Internal tracking issue #134](https://github.ibm.com/Watson-IoT/pal-tracking/issues/134)</sub>

### Describe the bug

On initial render, the tiles jump/move. They should be static from initial render.

resize rendering

### To Reproduce

1. [View the story in the storybook](https://carbon-addons-iot-react.com/?path=/story/watson-iot-dashboard-grid--dashboard-is-edtiable)
1. Flip between the different dashboard grid stories, you'll see the reflow only on the `isEditable` story

### Expected behavior

The cards are static on initial render, no moving. They move/flow only when the browser is resized to effect the layout of the cards.

### Environment/versions:

- OS: MacOS
- Browser: chrome
- `carbon-addons-iot-react` version: `v2.18.0`

### PR DESCRIPTION
**Pull request by sunilkotiyaibm**
Closes #780

**Summary**

- Dashboard Grid (dashboard,isEditable) : Tiles on dashboard grid is jump (animated) while rending the page. 

**Change List (commits, features, bugs, etc)**

src/components/Dashboard/DashboardGrid.jsx
src/components/Dashboard/__snapshots__/DashboardGrid.story.storyshot

**Acceptance Test (how to verify the PR)**

- Click on Dashboard (dashboard,isEditable) link, Dashboard tiles should be rendering static without animation

### CODE REVIEW

**Comment by sunilkotiyaibm** [comment]
@davidicus please review the PR#803 related the defect #780

**Comment by sunilkotiyaibm** [comment]
My observation regarding this defect:
Actually jumping of tile is not defect rather it is a animation feature which is related to shouldAnimate property, disabling this property stop jumping animating the tile. In this Dashboard (isEditable) link, knob can be added to enable/disable tile animation. 
For me this is not a defect.

**Comment by davidicus** [comment]
@scottdickerson I am not really seeing any ugliness. It def just snaps and doesn't animate anymore but doesn't look messed up to me. 




@lukefirth @amymillett @scottdickerson is this a preference that we can get a consensus on?

**Comment by davidicus** [comment]
I accidentally deleted my original comment instead of the broken gif I had in it. The animation does not look too horrible in the preview link, not sure if I am looking at the right thing, but I think we should defer to @scottdickerson preference here. @sunilkotiyaibm If there is a way to disable animation on load that would be preferable to just disabling it. @lukefirth opinions?

**Comment by lukefirth** [comment]
I'll be dumb- @davidicus would you mind re-adding your gif? :)

**Comment by sunilkotiyaibm** [comment]
> 
> I accidentally deleted my original comment instead of the broken gif I had in it. The animation does not look too horrible in the preview link, not sure if I am looking at the right thing, but I think we should defer to @scottdickerson preference here. @sunilkotiyaibm If there is a way to disable animation on load that would be preferable to just disabling it. @lukefirth opinions?

@davidicus animation is already disabled on on-load of tile in Dashboard Grid ( is Editable link), see the changed behavior here
https://deploy-preview-803--carbon-addons-iot-react.netlify.com

**Comment by davidicus** [comment]
> @davidicus animation is already disabled on on-load of tile in Dashboard Grid ( is Editable link), see the changed behavior here
> https://deploy-preview-803--carbon-addons-iot-react.netlify.com

Hi @sunilkotiyaibm. I see that it is disabled on load but it is never enabled afterwards. When trying to move components in the preview link there is no animation. Ideally, we could disable the animation when component is first loaded and then reenable afterwards as @scottdickerson was asking about here

>Ideally only the first positioning of the elements could disable the animation. Is it possible to somehow keep track whether this initial positioning has finished then turn on animation?

**Comment by davidicus** [comment]
@lukefirth

**Comment by davidicus** [comment]
@sunilkotiyaibm any updates here?

**Comment by davidicus** [comment]
@sunilkotiyaibm any update here for Scott's request?

**Comment by sunilkotiyaibm** [comment]
Hi @davidicus , @psdixit (pdixit2@us.ibm.com) is working this issue, I have discussed the scott concern with @psdixit. I will ask him to update on this PR.

**Comment by psdixit** [comment]
Hi @davidicus I did some changes on PR #803 based on your previous comments. Please review the same and provide your valuable input. 

Thanks,
PS Dixit

**Comment by tay1orjones** [comment]
closing in favor of #894

**Pull request closed without merging**
