### PR TITLE
fix(card): avoid clipping data state renderer error tooltip

### LINKED ISSUE #1198: [ValueCard] data state - error description runs off the page
### Describe the bug
On ValueCard for the data and error state, when you click on the description symbol, the information runs off the page

image

Go to https://carbon-addons-iot-react.com/?path=/story/watson-iot-valuecard--data-state-error-small.

Snapshot below shows issue:

image

### PR DESCRIPTION
**Pull request by tay1orjones**
Closes #1198

**Summary**

- Change the direction that data state tooltips are rendered on cards

**Change List (commits, features, bugs, etc)**

- items_here

**Acceptance Test (how to verify the PR)**

- view https://deploy-preview-1278--carbon-addons-iot-react.netlify.app/?path=/story/watson-iot-valuecard--data-state-error-small 
- also view the other data state stories
- the tooltip should render `right` instead of `bottom`

### CODE REVIEW

**Comment by bjornalm** [comment]
This will cause issues for RTL. Perhaps you could to use left side when in RTL?
image

**Comment by tay1orjones** [comment]
Ah, good observation @bjornalm. I think I can make this configurable so it can at the very least be handled at the application level.

**Comment by tay1orjones** [comment]
@bjornalm @sstone2423 PR has been updated to allow tooltip position to be configurable at the application level. Please re-review.

**Pull request merged**
