### PR TITLE
fix(pagewizard): add sticky footer

### PR DESCRIPTION
**Pull request by jessieyan**
Tracker #666 

Add a prop hasStickyFooter to PageWizard. 

If set to true, step actions will show up inside the sticky footer at the bottom of the page. 
If false, step actions button will show inside of step content.

image

image

### CODE REVIEW

**Comment by bryancboyd** [comment]
image

added a few tweaks to the footer styling

**Comment by davidicus** [comment]
Does this component have any design specs for it? I am wondering about the deviation in button size and placement from other components that are similar.

**Comment by bryancboyd** [comment]
Good points, @stuckless. This component (and the larger Form pattern) are
still in the design phase so I’m hesitant to make too many opinionated
behavioral choices now. Let’s push this through and open an issue in the
design repo to clarify this?

**Comment by stuckless** [comment]
@bryancboyd Sounds good.  I think it should be accounted for at some level.  Ideally their might a layout component that knows about sticky header, sticky footer and provides automatic scolling (or not), but if it existed, then, it could dropped into these kinds of template components and provide the behaviours automatically.

**Comment by bryancboyd** [comment]
@stuckless That's a solid idea; we have a shortage of layout components in the library at the moment, I think this would be a good thing to standardize on soon leveraging some of the layout models your team has developed already.

**Pull request merged**
