### PR TITLE
feat(table): variable sizes for row and column

### PR DESCRIPTION
**Pull request by scottdickerson**
**Summary**

- allow users to specify their own row height and column width for their tables

**Change List (commits, features, bugs, etc)**

- test(storybooksnaps): unfortunately storybook doesn't like styled components and throws a console error which I can ignore.  I don't want to fail the testcase because of that.
- feat(table): pass all props that are passed to our Table to the underlying CarbonTable, this allows users to easily use all the CarbonTable features and set a className for the table that they can use to perform their own styling
- test(table): add 3 stories to show how to apply each custom style to the table

**Related Issues**

- Closes IBM/carbon-addons-iot-react#36
- Closes IBM/carbon-addons-iot-react#46

**Acceptance Test (how to verify the PR)**

- check the 3 new stories, zebra, column width, and row height.

### CODE REVIEW

**Comment by bryancboyd** [comment]
A few things:

1) The column width isn't honored when filters are enabled, even if the column doesn't have a filter defined (as is the case with the `secretField` column)

```
<TableColumnWidth
  columns={tableColumns}
  data={tableData}
  actions={actions}
  options={{ hasFilter: true }}
  view={{ toolbar: { activeBar: 'filter' }}}
/>
```
image

2) In keeping with our desire to provide a "common design pattern" with easy escape hatch, could we add a prop on the column definition that allows the user to avoid passing in this for every column with a max width:

```
max-width: 20px; 
white-space: nowrap;
text-overflow: ellipsis; 
overflow-x: hidden;
```

Proposal:

```
{
  id: 'columnA',
  name: 'Column A',
  filter: { placeholderText: 'enter a value for this column' },
  width: 20,
}
```

This would automatically add the whitespace/overflow rules and max-width sizing.

**Comment by scottdickerson** [comment]
thanks for catching this @bryancboyd I've submitted an update that allows the same css based approach to work correctly if the filter row is enabled, rather than adding a new prop.

**Pull request merged**
