### PR TITLE
fix(table): 2233-Table-Checkbox-select-keyboard

### PR DESCRIPTION
**Pull request by sunilkotiyaibm**
#402

Closes #

**Summary**

In Table component, user is not able to select the checkbox using keyboard spacebar key, where as mouse click is working.

**Change List (commits, features, bugs, etc)**

src/components/Dashboard/__snapshots__/Dashboard.story.storyshot
src/components/Table/TableBody/TableBodyRow/TableBodyRow.jsx
src/components/Table/TableBody/TableBodyRow/TableBodyRow.test.jsx
src/components/Table/TableBody/TableBodyRow/__snapshots__/TableBodyRow.story.storyshot
src/components/Table/__snapshots__/Table.story.storyshot
src/components/TableCard/__snapshots__/TableCard.story.storyshot

**Acceptance Test (how to verify the PR)**

User not allow to select table records using keyboard as well as using mouse.

### CODE REVIEW

**Comment by sunilkotiyaibm** [comment]
@davidicus @tay1orjones please review PR  (703)
https://github.com/IBM/carbon-addons-iot-react/pull/703

**Comment by davidicus** [comment]
One thing to note if it helps, The action of row selection seems to be triggered with keyboard event but it is the styling for the checkmark that is not being changed.

**Comment by jessieyan** [comment]
@sunilkotiyaibm Hey Sunil, are you still working on this issue? Do you mind if I have a look at it?

**Comment by jessieyan** [comment]
Just talked with Bryan on this. We could not use TableSelectRow for this case because carbon x only provides either a TableSelectRow or a TableExpandRow.  And it would not suffice when we need both expansion and selection in a row.  I tested Sunil code and I approved the fix. @tay1orjones @davidicus @bryancboyd

**Comment by jessieyan** [comment]
Resolved conflicts in the branch.

**Pull request merged**
