### PR TITLE
fix(tablecard): improve isEditable state for timestamp columns

### PR DESCRIPTION
**Pull request by scottdickerson**
**Summary**

- improve the isEditable state to match the mockup for TableCard that Cynthia supplied
- fix(TableCard.story): removed story that was throwing console error until we can support this usecase without throwing console error

image

**Acceptance Test (how to verify the PR)**

- Verify the isEditable state

### CODE REVIEW

**Comment by CynZhang** [comment]
Should we also disable the interactions? search, filter, sort etc..

**Comment by scottdickerson** [comment]
great idea @CynZhang thanks for catching, I'll add disabling the toolbar controls if we're in this state

**Comment by scottdickerson** [comment]
I can't seem to disable sort, but I will disable the other toolbar controls @CynZhang

**Pull request merged**
