### PR TITLE
Page Hero

### PR DESCRIPTION
**Pull request by cgirani**
**Summary**

- Design updates on page hero, should handle normal, with action and with section

**Change List (commits, features, bugs, etc)**

- PageHero normal
- PageHero with action
- PageHero with section

**Related Issues**

- Closes IBM/carbon-addons-iot-react#NUMBER

**Acceptance Test (how to verify the PR)**

- tests here

### CODE REVIEW

**Comment by scottdickerson** [comment]
once quick question: 
image

the bottom padding/margin seems too large slightly

**Comment by cgirani** [comment]
@scottdickerson fixed the margin, there was a typo but also included values suggested by Amy.

**Comment by scottdickerson** [comment]
looks good thanks!

**Pull request merged**
