### PR TITLE
feat(progressindicator): vertical mode

### PR DESCRIPTION
**Pull request by cgirani**
**Summary**

- ProgressIndicator vertical design 

**Change List (commits, features, bugs, etc)**

- New prop for vertical design 

**Related Issues**

- Closes IBM/carbon-addons-iot-react#NUMBER

**Acceptance Test (how to verify the PR)**

- ProgressIndicator can be changed to vertical mode

### CODE REVIEW

**Comment by scottdickerson** [comment]
you may not need to do this as I hear that this is being done in Carbon X

**Comment by bryancboyd** [comment]
@scottdickerson we'll need to support a v9 style for our first use of this component, but when carbon-addons adds v10 support we can use the explicit vertical option

**Pull request merged**
