### PR TITLE
fix(imagecard): expansion and collapse doesn't work on firefox

### LINKED ISSUE #638: [TimeSeries] When the is editable bit is set the TimeSeries card isn't showing fake data
### Describe the bug

when the isEditable bit is set, the TimeSeries card isn't showing fake data

### To Reproduce

View the timeseries isEditable story, that should show fake data in the timeseries card

### PR DESCRIPTION
**Pull request by scottdickerson**
Closes #638

**Summary**

- Internal Bug reported where the Image Card didn't collapse from full screen correctly on firefox

**Change List (commits, features, bugs, etc)**

- refactor(ImageHotspots): pretty large refactor to remove the local container state from ImageHotspots and instead inherit the size from the Card content parent (which correctly handles Firefox)
- fix(TimeSeriesCard): isEditable is no longer showing fake data

**Acceptance Test (how to verify the PR)**

- Verify in Firefox the full screen image card dashboard story.  Expand and then collapse the image and ensure it is correctly positioned

### CODE REVIEW

**Comment by scottdickerson** [comment]
@tay1orjones that was actually a bug just in general with our zoom in and collapse, we should probably open a separate bug to track

**Comment by tay1orjones** [comment]
I've opened https://github.com/IBM/carbon-addons-iot-react/issues/648 for the issue found above.

**Pull request merged**
